name: create-branch
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ⚙️ CONFIGURANDO GIT
        run: |
          git config --local user.name "GitActionsBot"
          git config --local user.email "gitbot@git.com"
      - name: 🛠 CREANDO RAMA
        run: |
          git checkout develop
          git fetch
          git pull
          git checkout -b develop-main
          git push --set-upstream origin develop-main
